---
version: "2"

services:
  our-app:
    build: .
    environment:
      - MODE=dev
      - ELASTICSEARCH_HOST=127.0.0.1
      - ELASTICSEARCH_PORT=9200
    volumes:
      - .:/code
    depends_on:
      - elasticsearch
      - rabbitmq
    ports:
      - "9091:9090"

  activemq:
    image: rmohr/activemq:latest
    environment:
      - ACTIVEMQ_DEFAULT_USER=admin
      - ACTIVEMQ_DEFAULT_PASS=admin
    ports:
      - "8161:8161"
      - "61616:61616"

  elasticsearch:
    image: elasticsearch:5-alpine
    command: elasticsearch -Etransport.host=127.0.0.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ../data:/usr/share/elasticsearch/data